[theme]
primaryColor = "#FF4C60"  # Red/pink GPT highlight
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#1E1E1E"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[logger]
level = "info"
